#This is the publishing pipeline to publish the alternative cuda NuGet packages to the Azure DevOps feed
#The current alternative cuda version is 11.8
resources:
  pipelines:
  - pipeline: build
    source: 'CUDA-Zip-Nuget-Java-Packaging-Pipeline'
    trigger: 
      branches:
        include:
        - main
        - rel-*
    branch: main

parameters:
  - name: isReleaseBuild
    type: boolean
    default: false

variables:
  - name: ArtifactFeed
    ${{ if eq(parameters.isReleaseBuild, false) }}:
      value: rt-cuda-11-nightly
    ${{ else }}:
      value: onnxruntime-cuda-11

stages:
  - template: stages/nuget-cuda-publishing-stage.yml
    parameters:
      artifact_feed: $(ArtifactFeed)

  - template: stages/java-cuda-publishing-stage.yml
    parameters:
      artifact_feed: $(ArtifactFeed)