#This is the publishing pipeline to publish the cpu nuget package and default cuda NuGet packages to the Azure DevOps feed
#This is not used for the publishing to the official feed
#The current default cuda version is 12.2
resources:
  pipelines:
  - pipeline: build
    source: 'Zip-Nuget-Java-Nodejs Packaging Pipeline'
    trigger:
      branches:
        include:
        - main
        - rel-*
    branch: main

parameters:
  - name: isReleaseBuild
    type: boolean
    default: false

variables:
  - name: ArtifactFeed
    ${{ if eq(parameters.isReleaseBuild, false) }}:
      value: ORT-Nightly
    ${{ else }}:
      value: onnxruntime-cuda-12

stages:
  - template: templates/publish-nuget-steps.yml
    parameters:
      stage_name: 'Publish_NuGet_Package_And_Report'
      include_cpu_ep: true
      download_artifacts_steps:
        - download: build
          displayName: 'Download Pipeline Artifact - Signed NuGet Package'
          artifact: 'drop-signed-nuget-dml'
        - script: move "$(Pipeline.Workspace)\build\drop-signed-nuget-dml\*" $(Build.BinariesDirectory)\nuget-artifact\final-package

  # Publish CUDA 12 Nuget/Java pkgs to ADO feed
  - template: stages/nuget-cuda-publishing-stage.yml
    parameters:
      artifact_feed: $(ArtifactFeed)

  - template: stages/java-cuda-publishing-stage.yml
    parameters:
      artifact_feed: $(ArtifactFeed)
